source "https://rubygems.org"

gem "activesupport", "4.2.7"
gem "pronto", "~> 0.7" 
gem "pronto-brakeman"
gem "pronto-credo", "~> 0.0.4" 
gem "pronto-fasterer"
gem "pronto-flay"
gem "pronto-rails_best_practices"
gem "pronto-reek"
gem "pronto-rubocop"
