source "https://rubygems.org"

gem "pronto", github: "mmozuras/pronto"
gem "pronto-brakeman"
gem "pronto-coffeelint"
gem "pronto-credo", github: "carakan/pronto-credo"
gem "pronto-fasterer"
gem "pronto-flay"
gem "pronto-rails_best_practices"
gem "pronto-reek"
gem "pronto-rubocop"
